name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-and-norm:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install c_formatter_42
        run: pip install c_formatter_42

      - name: Format code
        run: |
          find . \( -name "*.c" -o -name "*.h" \) | grep -v "/.git/" | xargs -I {} c_formatter_42 {}

      - name: Commit formatted code
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && echo "No changes" && exit 0
          git add -u
          git commit -m "format: apply c_formatter_42"
          git push

      - name: Install Norminette
        run: pip install norminette

      - name: Run Norminette
        run: norminette src/ inc/

